### ISSUE TITLE
Variable substitution fails for boolean with value of false

### ISSUE THREAD

**Issue by rknorp** [jin-qu/jinqu-odata#24]
## jinqu-odata version
1.1.2

## Steps to reproduce
make queries like this:
1. service.createQuery(Project).where('x => (x.isDeleted === booleanVariable)', {booleanVariable: **true**}).toArrayAsync()
2. service.createQuery(Project).where('x => (x.isDeleted === booleanVariable)', {booleanVariable: **false**}).toArrayAsync()

## Expected  behavior
Expect urls like this:
1. https://localhost:44332/api/Projects?$filter=(isDeleted%20eq%20true)
2. https://localhost:44332/api/Projects?$filter=(isDeleted%20eq%20false)

## Actual behavior
Get urls like this:
1. https://localhost:44332/api/Projects?$filter=(isDeleted%20eq%20true) (this one works OK)
2. https://localhost:44332/api/Projects?$filter=(isDeleted%20eq%20booleanVariable) (variable substitution fails)

I think the issue may be on line 217 of shared.ts:
`return (scope && valueToStr(scope[name])) || name;`

Changing it to this solves the issue for me:
`return scope ? valueToStr(scope[name]) : name;`

**Comment by mfranchi** [comment]
This same behavior occurs with any variable, not just booleans.

I ran into this same issue and was able to get it working by providing the `scopes` parameter along with a `predicate` function. 

`
service.createQuery(Project).where(x => x.id === variableName, { 
variableName: variableName 
});
`

In your example code, it looks like you're using a string instead of a `predicate` function, and that may be your issue.

The documentation for this library leaves a LOT to be desired, but hopefully this works for you.

**Comment by umutozel** [comment]
Thanks for the feedback. I started working on it now, and yeah documentation still needs serious work. Hopefully after these intense weeks I'll plan to spend some time on it. Any ideas are welcome.
